app/routes/activo_general.py
from flask import Blueprint, render_template, redirect, url_for, request
from app.models.userModels import db, ActivoGeneral, Categoria, Marca
from app.forms import AgregarActivoGeneralForm, AgregarCategoriaForm, AgregarMarcaForm
from flask_login import login_required

activos_bp = Blueprint('activos', __name__, url_prefix='/activos')

@activos_bp.route('/', methods=['GET'])
@login_required
def listar_activos():
    form = AgregarActivoGeneralForm()
    form2 = AgregarCategoriaForm()
    form3 = AgregarMarcaForm()
    #la variable personal tiene una consulta que trae de manera conjunta el departemento y cargo de cada personal
    activo_general = ActivoGeneral.query.all()
    marcas = Marca.query.all()
    categorias = Categoria.query.all()
    return render_template('activos_generales.html', form=form, form2=form2, form3=form3, activo_general=activo_general, marcas=marcas, categorias=categorias)

@activos_bp.route('/agregar', methods=['GET', 'POST'])
@login_required
def agregar_activo_general():
    form = AgregarActivoGeneralForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            # Aquí procesas los datos del formulario y creas un nuevo activo general
            # Puedes usar form.<campo>.data para acceder a los datos del formulario

            categoria_nombre = Categoria.query.get(form.categoria_id.data).nombre_categoria
            marca_nombre = Marca.query.get(form.marca_id.data).nombre_marca

            nuevo_activo = ActivoGeneral(
                categoria_id=form.categoria_id.data,
                marca_id=form.marca_id.data,
                modelo=form.modelo.data,
                nombre = f"{categoria_nombre} - {marca_nombre} - {form.modelo.data}",
                cantidad_total=form.cantidad_total.data,
                cantidad_disponible=form.cantidad_disponible.data
            )
            db.session.add(nuevo_activo)
            db.session.commit()
        else:
            print("El formulario NO ES VALIDO")
        return redirect(url_for('activos.listar_activos'))  # Redirecciona después de agregar
    
    return render_template('activos_generales.html', form=form)

@activos_bp.route('/agregar-categoria', methods=['GET', 'POST'])
@login_required
def agregar_categorias():
    form = AgregarCategoriaForm()
    if form.validate_on_submit():
        nombre_categoria = form.nombre_categoria.data
        categoria = Categoria(nombre_categoria = nombre_categoria)
        db.session.add(categoria)
        db.session.commit()
        #después de realizar el respectivo commit se redirecciona a la misma ruta para listar las categorias
        return redirect(url_for('activos.listar_activos'))
    #categorias = Categoria.query.all()
    return render_template('activos_generales.html')

@activos_bp.route('/agregar-marca', methods=['GET', 'POST'])
@login_required
def agregar_marcas():
    form = AgregarMarcaForm()
    if form.validate_on_submit():
        nombre_marca = form.nombre_marca.data
        marca = Marca(nombre_marca=nombre_marca)
        db.session.add(marca)
        db.session.commit()
        #después de realizar el respectivo commit se redirecciona a la misma ruta para listar las categorias
        return redirect(url_for('activos.listar_activos'))
    #marcas = Marca.query.all()
    return render_template('activos_generales.html') 

app/routes/asignacion.py
from flask import Blueprint, render_template, redirect, url_for, request, jsonify
from app.forms import AsignarPersonalActivoForm, datetime
from app.models.userModels import db, Personal, Activo, Departamento, HistorialActivo, ActivoGeneral, Categoria
from flask_login import login_required

asignacion_bp = Blueprint('asignacion', __name__, url_prefix='/asignacion')

@asignacion_bp.route('/usuarios/<int:departamento_id>', methods=['GET'])
@login_required
def obtener_usuarios(departamento_id):
    usuarios = Personal.query.filter_by(departamento_id=departamento_id).all()  # Filtrar usuarios por departamento
    usuarios_json = [{'id': usuario.id_dni, 'nombre_completo': usuario.nombres_completos} for usuario in usuarios]
    return jsonify(usuarios_json)

@asignacion_bp.route('/asignar_activos', methods=['GET', 'POST'])
@login_required
def asignar_activos():
    activos_seleccionados = request.args.get('activos').split(',')
    #si se ingresa a la página sin un activo seleccionado o colocado en la url, se devuelve a la página de activos
    if(activos_seleccionados[0]==''):
        return redirect(url_for('activo.listar_activos'))
    else:
        form = AsignarPersonalActivoForm(request.form)  # Pasar los datos del formulario al crear la instancia
        # Traer los datos de todos los departamentos
        departamentos = Departamento.query.all() 
        # Cargar las opciones de departamentos en el campo ubicacion
        form.ubicacion.choices = [(d.id, d.nombre_departamento) for d in departamentos]

    return render_template('asignar_activos_un_personal.html', activos_seleccionados=activos_seleccionados, form=form)

@asignacion_bp.route('/guardar_asignacion', methods=['POST'])
@login_required
def guardar_asignacion():
    form = AsignarPersonalActivoForm(request.form)  # Pasar los datos del formulario al crear la instancia

    if form.validate_on_submit():
        activos_seleccionados = form.activos_seleccionados.data.split(',')
        nro_cargo = form.nro_cargo.data
        ubicacion = form.ubicacion.data
        responsable = form.responsable.data

        fecha_actual = datetime.now()
        
        # se modifican los activos individuales y se registran en el historial
        for num_serie in activos_seleccionados:
            activo = Activo.query.get(num_serie)
            if activo:
                activo.nro_cargo = nro_cargo
                activo.ubicacion = ubicacion
                activo.responsable = responsable

                # Registrar en el historial de activos
                
                historial = HistorialActivo(
                    activo_id=num_serie,
                    evento='salida',
                    fecha=fecha_actual,
                    detalles = f'Se ha asignado este activo al personal (DNI: {responsable})'
                    )
                db.session.add(historial)
                db.session.commit()

                # Actualizar la cantidad disponible en la tabla de activos generales
                activo_general = activo.activo_general
                if activo_general:
                    activo_general.cantidad_disponible -= 1
                    db.session.commit()

    return redirect(url_for('activo.listar_activos'))

app/routes/auth.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_user, logout_user, login_required, current_user
from app.models.userModels import User, db
from app.forms import AdminLoginForm, AdminRegisterForm

#uso de blueprints para el manejo de rutas
auth_bp = Blueprint('auth', __name__)

#se establece como ruta principal, ya que se debe hacer un login desde la ruta auth para poder acceder al sistema

@auth_bp.route('/')
@login_required
def inicio():
    return render_template('index.html')

@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('auth.inicio'))

    form = AdminLoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        user = User.query.filter_by(username=username).first()
        if user and user.check_password(password):
            login_user(user)
            return redirect(url_for('auth.inicio'))
        else:
            print("Error")
            #print(username)
            #print(password)
            #se podría colocar un mensaje
            #flash('Invalid username or password.', 'danger')
    return render_template('login.html', form=form)


@auth_bp.route('/register', methods=['GET', 'POST'])
@login_required
def register():
    form = AdminRegisterForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        existing_user = User.query.filter_by(username=username).first()
        if existing_user:
            #flash('Username already exists. Please choose a different one.', 'danger')
            print("")
        else:
            new_user = User(username=username)
            new_user.set_password(password)
            db.session.add(new_user)
            db.session.commit()
            return redirect(url_for('auth.inicio'))
    return render_template('register.html', form=form)

@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.inicio'))

app/routes/cargo.py
from flask import Blueprint, render_template, redirect, url_for
from app.models.userModels import db, Cargo, Departamento
from app.forms import AgregarCargoForm
from flask_login import login_required

#se usa para obtener información de dos tablas relacionadas
from sqlalchemy.orm import joinedload
#se usa para obtener los resultados de una consulta de manera ordenada
from sqlalchemy import asc

cargos_bp = Blueprint('cargos', __name__, url_prefix='/cargos')

@cargos_bp.route('/', methods=['GET', 'POST'])
@login_required
def listar_cargos():
    form = AgregarCargoForm()
    if form.validate_on_submit():
        nombre_cargo = form.nombre_cargo.data
        id_departamento = form.departamento_id.data
        departamento = Departamento.query.get(id_departamento)
        if departamento:
            cargo = Cargo(nombre_cargo=nombre_cargo, departamento_id=departamento.id)
            db.session.add(cargo)
            db.session.commit()
            return redirect(url_for('cargos.listar_cargos'))

    cargos = Cargo.query.options(joinedload(Cargo.cargo_departamento)).order_by(asc(Cargo.departamento_id)).all()
    return render_template('cargos.html', form=form, cargos=cargos)

app/routes/categoria.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_required
from app.models.userModels import Categoria, db
from app.forms import AgregarCategoriaForm

categorias_bp = Blueprint('categorias', __name__, url_prefix='/categorias')

@categorias_bp.route('/', methods=['GET', 'POST'])
@login_required
def listar_categorias():
    form = AgregarCategoriaForm()
    if form.validate_on_submit():
        nombre_categoria = form.nombre_categoria.data
        categoria = Categoria(nombre_categoria = nombre_categoria)
        db.session.add(categoria)
        db.session.commit()
        #después de realizar el respectivo commit se redirecciona a la misma ruta para listar las categorias
        return redirect(url_for('categorias.listar_categorias'))
    categorias = Categoria.query.all()
    return render_template('categorias.html', categorias=categorias, form=form) 

app/routes/personal.py
from flask import Blueprint, render_template, redirect, url_for, jsonify, flash, request
from app.models.userModels import Personal, Cargo, ActivoGeneral, Categoria, Marca, Activo
from app.forms import AgregarPersonalForm, AsignarActivoForm, EditarPersonalForm
from app.models.userModels import db
from sqlalchemy.orm import joinedload
from flask_login import login_required

#el blueprint consta con un url y un prefijo, lo que hace es convertir a su ruta '/' en la de /personal
#de esa forma se puede manejar una navegación más ordenada
personal_bp = Blueprint('personal', __name__, url_prefix='/personal')

@personal_bp.route('/', methods=['GET'])
@login_required
def listar_personal():
    form = AgregarPersonalForm()
    form2 = EditarPersonalForm()
    #la variable personal tiene una consulta que trae de manera conjunta el departemento y cargo de cada personal
    personal = Personal.query.options(joinedload(Personal.departamento), joinedload(Personal.cargo)).all()
    return render_template('personal.html', form=form, form2=form2,personal=personal)

@personal_bp.route('/agregar', methods=['POST'])
@login_required
def agregar_personal():
    #instancia del formulario
    form = AgregarPersonalForm()

    if request.method == 'POST':
        if form.validate_on_submit():
            #print("El formulario es validado")
            #El formulario se ha validado correctamente, proceder con la creación del personal
            personal = Personal(
                id_dni=form.id_dni.data,
                departamento_id=form.departamento_id.data,
                cargo_id=form.cargo_id.data,
                apellido_p=form.apellido_p.data,
                apellido_m=form.apellido_m.data,
                nombres=form.nombres.data,
                nombres_completos=form.nombres_completos.data,
                usuario=form.usuario.data,
                fecha_registro=form.fecha_registro.data,
                estado=form.estado.data,
                fecha_cese=form.fecha_cese.data,
                celular_personal=form.celular_personal.data
            )

            db.session.add(personal)
            db.session.commit()
        else:
            print("El formulario NO ES VÁLIDO")
        return redirect(url_for('personal.listar_personal'))

    return render_template('personal.html', form=form)

#ruta para obtener los datos del personal
#los datos deberán de ser obtenido por medio de una petición del tipo ajax fetch y ser cargados en el formulario
#en base a lo que retorne esta lista, datos en tipo jsonify

@personal_bp.route('/obtener_datos_personal/<string:id_dni>', methods=['GET'])
def obtener_datos_personal(id_dni):
    personal = Personal.query.filter_by(id_dni=id_dni).first()
    if personal is None:
        return jsonify({'error': 'Personal no encontrado'}), 404
    return jsonify({
        'id_dni': personal.id_dni,
        'departamento_id': personal.departamento_id,
        'cargo_id': personal.cargo_id,
        'apellido_p': personal.apellido_p,
        'apellido_m': personal.apellido_m,
        'nombres': personal.nombres,
        'nombres_completos': personal.nombres_completos,
        'usuario': personal.usuario,
        'fecha_registro': personal.fecha_registro.strftime('%Y-%m-%d'),
        'estado': personal.estado,
        'fecha_cese': personal.fecha_cese.strftime('%Y-%m-%d') if personal.fecha_cese else None,
        'celular_personal': personal.celular_personal
    }), 200


# @personal_bp.route('/editar_personal/<id>', methods=['GET', 'POST'])
# def editar_personal(id):
#     personal = Personal.query.get_or_404(id)
#     form2 = EditarPersonalForm(personal=personal)
#     if form2.validate_on_submit():
#         # Actualiza los datos del personal en la base de datos
#         personal.id_dni = form2.id_dni.data
#         personal.departamento_id = form2.departamento_id.data
#         personal.cargo_id = form2.cargo_id.data
#         personal.apellido_p = form2.apellido_p.data
#         personal.apellido_m = form2.apellido_m.data
#         personal.nombres = form2.nombres.data
#         personal.nombres_completos = form2.nombres_completos.data
#         personal.usuario = form2.usuario.data
#         personal.fecha_registro = form2.fecha_registro.data
#         personal.estado = form2.estado.data
#         personal.fecha_cese = form2.fecha_cese.data
#         personal.celular_personal = form2.celular_personal.data
#         db.session.commit()
#     return render_template('personal.html', form2=form2)



#ruta en donde se realizará la consulta json para obtener información
@personal_bp.route('/cargos/<int:departamento_id>', methods=['GET'])
@login_required
def obtener_cargos(departamento_id):
    #se desea obtener información respecto a los cargos
    cargos = Cargo.query.filter_by(departamento_id=departamento_id).all() # Filtra los cargos por el departamento seleccionado
    cargos_json = [{'id': cargo.id, 'nombre_cargo': cargo.nombre_cargo} for cargo in cargos]
    return jsonify(cargos_json)

#vista de personal para poder asignar activos
#probando
@personal_bp.route('/asignar-activo/<int:empleado_id>', methods=['GET', 'POST'])
@login_required
def asignar_activo(empleado_id):
    empleado = Personal.query.get_or_404(empleado_id)
    form = AsignarActivoForm()

    # Obtener activos disponibles para asignar
    activos_disponibles = Activo.query.filter_by(responsable=None).all()
    categorias = Categoria.query.all()
    marcas = Marca.query.all()

    print(activos_disponibles)
    return render_template('asignar-activo.html', empleado=empleado, form=form, activos_disponibles=activos_disponibles, categorias=categorias, marcas=marcas)

@personal_bp.route('/api/marcas/<int:categoria_id>', methods=['GET'])
@login_required
def obtener_marcas(categoria_id):
    marcas = Marca.query.filter_by(categoria_id=categoria_id).all()
    marcas_json = [{'id': marca.id, 'nombre_marca': marca.nombre_marca} for marca in marcas]
    return jsonify(marcas_json)

@personal_bp.route('/api/activos-disponibles/<int:empleado_id>/<int:categoria_id>/<int:marca_id>', methods=['GET'])
@login_required
def obtener_activos_disponibles(empleado_id, categoria_id, marca_id):
    activos_disponibles = ActivoGeneral.query.filter(ActivoGeneral.categoria_id==categoria_id, ActivoGeneral.marca_id==marca_id, ActivoGeneral.cantidad_disponible > 0).all()
    activos_json = [{'modelo': activo.modelo} for activo in activos_disponibles]

    return jsonify(activos_json)

app/templates/activos_generales.html
{% extends 'base.html' %}
{% block title %}Activos Generales{% endblock %}

{% block content %}
<div class="activos-generales-titulo row my-2">
    <h1 class="col-md-4">Activos Generales</h1>
    <div class="titulo-botones col-md-4 ms-auto">
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#agregarCategoriaModal" id="boton-agregarCategoria">Añadir Categoría</button>
        &nbsp;
        <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#agregarMarcaModal" id="boton-agregarMarca">Añadir Marca</button>
    </div>
</div>
    
    <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#filtroModal" id="abrir-filtro">
        <i class="fa-solid fa-filter"></i>
    </button>

    <div class="table-responsive">
        <table class="table table-hover">
            <thead class="table-dark">
                <tr>
                   <th>Categoría</th>
                   <th>Marca</th>
                   <th>Modelo</th>
                   <th>Cantidad Disponible</th>
                   <th>Cantidad Total</th>
                   <th>Edit.</th>
                </tr>
             </thead>
             <tbody>
                {% for activog in activo_general %}
              <tr >
                <td>{{ activog.categoria.nombre_categoria }}</td>
                <td>{{ activog.marca.nombre_marca }}</td>
                <td>{{ activog.modelo }}</td>
                <td>{{ activog.cantidad_disponible }}</td>
                <td>{{ activog.cantidad_total }}</td>
                <td><button class="btn btn-outline-warning btn-editar-activo-general"><i class="fa-solid fa-gear"></i></button></td>
              </tr>
              {% endfor %}
              </tbody>
        </table>
    </div>

    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#agregarActivoGModal" id="boton-agregar">
        <i class="fa-solid fa-plus"></i>
    </button>
    <!-- Modal para activo general -->
    <div class="modal fade" id="agregarActivoGModal" tabindex="-1" aria-labelledby="agregarActivoGLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="agregarActivoGModalLabel">Agregar Actigo General</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form method="POST" action="{{ url_for('activos.agregar_activo_general') }}">
                        {{ form.hidden_tag() }}  <!-- Añade campos ocultos para seguridad -->
                        <div class="form-group">
                            {{ form.categoria_id.label(class="form-label") }}
                            {{ form.categoria_id(class="form-control") }}
                        </div>
                        
                        <div class="form-group">
                            {{ form.marca_id.label(class="form-label") }}
                            {{ form.marca_id(class="form-control") }}
                        </div>
                        
                        <div class="form-group">
                            {{ form.modelo.label(class="form-label") }}
                            {{ form.modelo(class="form-control") }}
                        </div>

                        <div class="form-group" id="form-nombre">
                            {{ form.nombre.label(class="form-label") }}
                            {{ form.nombre(class="form-control") }}
                        </div>
                        
                        <div class="form-group">
                            {{ form.cantidad_total.label(class="form-label") }}
                            {{ form.cantidad_total(class="form-control") }}
                        </div>
                        
                        <div class="form-group">
                            {{ form.cantidad_disponible.label(class="form-label") }}
                            {{ form.cantidad_disponible(class="form-control") }}
                        </div>
                        <br>
                        <button type="submit" class="btn btn-primary">Agregar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal para filtrar activos generales -->
    <div class="modal fade" id="filtroModal" tabindex="-1" aria-labelledby="filtroModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="filtroModalLabel">Filtrar por Categoría y/o Marca</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="filtroForm">
                        <div class="mb-3">
                            <p for="categorias">Categorías:</p>
                            <!-- Checkbox para categorías -->
                            {% for categoria in categorias %}
                            <label><input type="checkbox" name="categorias" value="{{ categoria.nombre_categoria }}"> {{ categoria.nombre_categoria }}</label><br>
                            {% endfor %}
                        </div>
                        <div class="mb-3">
                            <p for="marcas">Marcas:</p>
                            <!-- Checkbox para marcas -->
                            {% for marca in marcas %}
                            <label><input type="checkbox" name="marcas" value="{{ marca.nombre_marca }}"> {{ marca.nombre_marca }}</label><br>
                            {% endfor %}
                        </div>
                        <button type="submit" class="btn btn-primary">Buscar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal para agregar categoría -->
    <div class="modal fade" id="agregarCategoriaModal" tabindex="-1" aria-labelledby="agregarCategoriLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="agregarCategoriaModalLabel">Agregar Categoria</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form method="POST" action="{{ url_for('activos.agregar_categorias') }}">
                        {{ form2.hidden_tag() }}  <!-- Añade campos ocultos para seguridad -->
                        <div class="form-group">
                            <label for="{{ form2.nombre_categoria.id }}">Nombre Categoría</label>
                            {{ form2.nombre_categoria(class="form-control", id=form2.nombre_categoria.id) }}
                        </div>
                        <div class="modal-footer">
                            {{ form2.submit(class="btn btn-primary btn-form-categoria") }}
                        </div>
                    </form>
                    <br>
                    <ul class="listas">
                        {% for cat in categorias %}
                        <li class="cat-nombres" id="{{cat.nombre_categoria}}">{{cat.nombre_categoria}}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal para agregar Marca -->
    <div class="modal fade" id="agregarMarcaModal" tabindex="-1" aria-labelledby="agregarMarcaLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="agregarMarcaModalLabel">Agregar Marca</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form method="POST" action="{{ url_for('activos.agregar_marcas') }}">
                        {{ form3.hidden_tag() }}
                        <div class="form-group">
                            <label for="{{ form3.nombre_marca.id }}">Nombre Marca</label>
                            {{ form3.nombre_marca(class="form-control", id=form3.nombre_marca.id) }}
                        </div>
                        <div class="modal-footer">
                            {{ form3.submit(class="btn btn-primary btn-form-marca") }}
                        </div>
                    </form>
                    <br>
                    <ul class="listas">
                        {% for mar in marcas %}
                        <li class="mar-nombres" id="{{mar.nombre_marca}}">{{mar.nombre_marca}}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <style>
        #form-nombre{
            display: none;
        }

        #abrir-filtro{
            position: fixed;
            border-radius: 50%;
            height: 40px; 
            right: 30px;
            bottom: 190px;
            box-shadow: rgba(0, 0, 0, 0.19) 0px 10px 20px, rgba(0, 0, 0, 0.23) 0px 6px 6px;
        }

        #boton-agregar{
            position: fixed;
            border-radius: 50%;
            height: 40px; 
            right: 30px;
            bottom: 120px;
            box-shadow: rgba(0, 0, 0, 0.19) 0px 10px 20px, rgba(0, 0, 0, 0.23) 0px 6px 6px;
        }
    </style>

    <script>
        // se obtiene el formulario de filtro para agregarle un evento del tipo submit
        // ejecuta la funcion 'filtrarResultados' cuando se ejecute dicho evento
        // termina ocultando el formulario
        document.getElementById('filtroForm').addEventListener('submit', function(e) {
            e.preventDefault();
            filtrarResultados();
            $('#filtroModal').modal('hide');
        });

        //funcion para filtrar los resltados en base a la funcion obtenerSeleccion
        function filtrarResultados() {
            //se usan los resultados que cumplan con la condicion de contar con categorias
            let categoriasSeleccionadas = obtenerSeleccion('categorias');
            //se usan los resultados que cumplan con la condicion de contar con marcas
            let marcasSeleccionadas = obtenerSeleccion('marcas');

            // obtiene todos los elementos que sean del tipo tbody tr
            let filas = document.querySelectorAll('tbody tr');
            // filas al ser un arreglo ejecuta una función para cada elemento obtenido
            filas.forEach(function(fila) {
                // se obtiene el valor textual de cada elemento
                let categoriaEnFila = fila.querySelector('td:nth-child(1)').textContent;
                let marcaEnFila = fila.querySelector('td:nth-child(2)').textContent;

                // devolverá un valor del tipo boolean
                // compara el valor del texto obtenido por fila, existe dentro del arreglo obtenido en la funcion 'obtenerSeleccion()'
                let categoriaCoincide = categoriasSeleccionadas.includes(categoriaEnFila) || categoriasSeleccionadas.includes('todos');
                let marcaCoincide = marcasSeleccionadas.includes(marcaEnFila) || marcasSeleccionadas.includes('todos');

                // condicion
                if ((categoriasSeleccionadas.length === 0 || categoriaCoincide) && (marcasSeleccionadas.length === 0 || marcaCoincide)) {
                    fila.style.display = 'table-row';
                } else {
                    fila.style.display = 'none';
                }
            });
        }

        //funcion para obtener a los checkbo que han sido seleccionados, estos valores se guaradan en un arreglo
        function obtenerSeleccion(nombreCheckbox) {
            let seleccion = [];
            let checkboxes = document.querySelectorAll('input[name="' + nombreCheckbox + '"]:checked');
            checkboxes.forEach(function(checkbox) {
                seleccion.push(checkbox.value);
            });
            return seleccion;
        }

        //funcio para animacion
        let btnEditarActivo = document.querySelectorAll(".btn-editar-activo-general")
        btnEditarActivo.forEach(function(e){
            e.addEventListener("mouseover", function(){
                e.querySelector("i").classList.add("fa-spin")
            })

            e.addEventListener("mouseout", function(){
                e.querySelector("i").classList.remove("fa-spin")
            })
        })
    </script>


{% endblock %}

app/templates/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="row justify-content-center align-items-center mt-5">
    <div class="col-md-4 border rounded-4 shadow py-4 px-3">
        <form method="POST" action="{{ url_for('auth.login') }}">
            <h2 class="mb-4">Acceder</h2>
            {{ form.hidden_tag() }}
            <div class="form-floating mb-4">
                {{ form.username(class="form-control", size=20, placeholder='-') }}
                {{ form.username.label(for='username')}}
            </div>
            <div class="form-floating mb-4">
                {{ form.password(type='password', class="form-control", size=20, placeholder='-')}}
                {{ form.password.label(for='password')}}
            </div>
            <div>{{ form.submit(class='btn btn-primary') }}</div>
        </form>
    </div>
</div>
{% endblock %}